import javax.swing.*;

public class ATMGUI extends JFrame{
    //GUI is built using IntelliJ's swing editor
    //Details are stored in ATMGUI.form, and were generated by the editor
    protected JPanel panel;
    protected JButton balanceButton;
    protected JButton withdrawButton;
    protected JButton depositButton;
    protected JTextField input;
    protected JButton enterButton;
    protected JButton cancelButton;
    protected JLabel screen;
    protected JButton yesButton;
    protected JButton noButton;
    private ATM atm; //view is aware of the model

    //constructor
    public ATMGUI(ATM atm){
        setSize(500, 500);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setVisible(true);
        setContentPane(panel);
        this.atm = atm;
        this.screen.setText(atm.getScreen(atm.getCurrentScreen()));
    }

    //update the labeled based on the current screen
    public void changeScreen(){
        this.screen.setText(atm.getScreen(atm.getCurrentScreen()));
    }
}
